artists/urls.py
from django.urls import path

from . import views

app_name = "artists"

urlpatterns = [
    # https://docs.djangoproject.com/en/5.0/ref/urls/#django.urls.path
    path(
        route="",
        view=views.IndexView.as_view(),
        name="index",
    ),
    path(
        # generally, str won't work
        # route="<str:name>/",
        route="<int:pk>/",
        view=views.DetailView.as_view(),
        name="detail",
    ),
]

djamp/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path(
        "artists/",
        include("artists.urls"),
    ),
    path("admin/", admin.site.urls),
]

artists/models.py
from django.db import models

# ./manage.py migrate
# ./manage.py makemigrations
# ./manage.py migrate


# https://stackoverflow.com/q/66142733

# artists must be unique
# an artist has one or more albums
#
# albums must not be unique (e.g. 'Demo')
# an album is 'owned' by one or more artists


class Artist(models.Model):
    name = models.TextField(unique=True)

    def __str__(self) -> str:
        return self.name


class Album(models.Model):
    name = models.TextField()

    artist = models.ForeignKey(
        to=Artist,
        on_delete=models.CASCADE,
        # verbose_name="Journal",
    )

    # artist = models.ManyToManyField(to=Artist)

    year = models.IntegerField(
        # TODO: int bounds, or year-only date
        # min_value="1920",
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["artist", "name", "year"],
                name="artist_album_year",
            )
        ]

    def __str__(self) -> str:
        return self.name

    # def __repr__(self) -> str:
    #     return f"Album: {self.name}"  # \nYear: {self.year}"
    #
    # def get_artist(self):  # -> Artist:
    #     return self.artist.values_list("name")
    #
    # def as_dict(self) -> dict:
    #     return {
    #         "Album": self.name,
    #         "Artist": self.artist,
    #         "Year": self.year,
    #     }

artists/views.py
from django.shortcuts import render
from django.views import generic

from artists.models import Artist


class IndexView(generic.ListView):
    template_name = "artists/index.html"  # default: <app name>/<model name>_list.html

    context_object_name = "artist_list"

    def get_queryset(self):  # -> _SupportsPagination[_M]:
        # return Artist.objects.all()  # .order_by("pk")
        return Artist.objects.filter().order_by("name")


class DetailView(generic.DetailView):
    model = Artist

artists/templates/artists/artist_detail.html
<h1>
    <!-- TODO: table -->
    <a href="{% url 'artists:detail' artist.pk %}">{{ artist.name }}</a>
</h1>
{% for x in artist.album_set.all %}<li>{{ x.name }}</li>{% endfor %}

artists/templates/artists/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'artists/style.css' %}" />
<!-- TODO: search bar -->
<!-- TODO: incremental search / autocomplete -->
<!-- https://openfolder.sh/django-tutorial-as-you-type-search-with-ajax -->
<!-- https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html -->
{% if artist_list %}
    <ul>
        {% for artist in artist_list %}
            <li>
                <!-- explicit namespacing `app_name` to be declared in artists/urls.py -->
                <a href="{% url 'artists:detail' artist.pk %}">{{ artist.name }}</a>
                <!-- <a href="foo">{{ artist.name }}</a> -->
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No artists are available.</p>
{% endif %}